# Generated by Django 5.2.17 on 2026-09-21 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('college', models.CharField(blank=True, default='', max_length=150)),
                ('course', models.CharField(blank=True, default='', max_length=120)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('year', models.CharField(blank=True, default='', max_length=20)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('budget', models.CharField(blank=True, default='', max_length=60)),
                ('preferred_room_type', models.CharField(blank=True, default='', max_length=40)),
                ('mother_name', models.CharField(blank=True, default='', max_length=120)),
                ('father_name', models.CharField(blank=True, default='', max_length=120)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('mobile_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(db_index=True, max_length=160)),
                ('kind', models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email')], db_index=True, max_length=10)),
                ('otp_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('max_resends', models.PositiveIntegerField(default=3)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='accounts.student')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
