# Generated by Django 5.2.17 on 2026-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Owner'), ('admin', 'Admin')], db_index=True, default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
